### PR TITLE
Implemented taking avi file as argument for input & fixed a couple of issues

### PR DESCRIPTION
**Pull request by sundaram75**
1. Implemented taking avi file as argument for input instead of webcam ( Useful for testing and debugging ).
2. Fixed compile error in // Show and save webcam out and preview.
3. Fixed runtime error occuring due to wrong parameter to Canny . ( failing with error Aperture size should be odd number . Fails even though the argument is odd . Fixed by passing eSize (3) instead of wSize (11) as argument.

### CODE REVIEW

**Comment by ryanpeach** [comment]
Did you keep the original method or overwrite it? It appears to be overwritten, please separate them into two distinct methods.

**Comment by sundaram75** [comment]
It's separated now ..

**Comment by ryanpeach** [comment]
Very cool implementation.

**Comment by ryanpeach** [comment]
I'm sorry to ask, but please resubmit, the merge did not contain changes to capture.cpp as intended.

**Comment by ryanpeach** [comment]
Never mind, I've got the file git is just acting weird.

**Pull request merged**
