### PR TITLE
Implemented the logging functionality using log4cpp library

### PR DESCRIPTION
**Pull request by sundaram75**
Hi Ryan,
              I have implemented the logger on the main branch and written a small  snippet in the capture.cpp.

Before building log4cpp library needs to be installed. I'll check and see what changes need to be made to the dependencies script for the same. Meanwhile issue the following command to install it manually

$ sudo apt-get install liblog4cpp5v5
$ sudo apt-get install liblog4cpp5-dev
$ sudo apt-get install liblog4cpp-doc

Right now not sure if this will work for the android branch as i read somewhere last week that the library for android is different.

Please review and provide your comments.

Also i'm not sure if the $(LOGFLAGS) is absolutely necessary while compiling all the files.
I thought i'll push it before i break something while trying to optimize. 
Will remove it later if not necessary.

Thanks
Sundaram

### CODE REVIEW

**Comment by ryanpeach** [comment]
I am happy how modular you made your modifications, good job! It will make merging much easier with the number of modifications I have made around the project. I will not be able to test it until 5pm CT, but then I will let you know! Again, thank you  very much for your help!

As per your txt logging recommendations, I would like the system to record both an image of the last 3 frames which contain "information" such as focus points, borders, etc (not just ALL frames) and then also a corresponding text file listing the information contained in these images. The same should be done for the last 3 "previews." This will greatly help debugging in the future. Will this library make this easy?

**Comment by ryanpeach** [comment]
Also, as I said previously, please upload your logging recommendations to the wiki for viewing and editing. Thanks again!

**Comment by sundaram75** [comment]
Yes .That is exactly what i had in mind when i designed the structure of the log files.  this information is supposed to be dumped into trace.log .trace.log will be a rolling log. We can limit the size of the log such that only 3 frames can be accommodated. So only information of the last 3 frames is stored in the trace.log file.Once the log file exceeds the size of the 3 frames.it'll roll over to a backup file with name trace.log.1 . We can have as many backup files as we want to. It can be just set in the properties file and no recompile is needed.
One assumption here is that the size of data written for each frame is the same. Is that a safe assumption to make ?
I'll try to implement it tomorrow .

**Comment by ryanpeach** [comment]
Yes that assumption will be fine except for on the preview images (the output page varies it's size depending on the size of the area it takes up on the webcam).

Regards,Ryan Peach

Date: Tue, 8 Dec 2015 07:08:15 -0800

**Pull request merged**
